destination         : _static/
layouts_dir         : _layouts/
data_dir            : _data/
includes_dir        : _includes/
sass_dir            : _sass/

page_gen-dirs: true
page_gen:
  - data: artwork      # The name of the data file
    template: artwork  # The layout to use
    name: title        # The field to use as the page name
    dir: artwork       # The dir to store in pages in
  - data: albums
    template: album
    name: title
    dir: albums
